### PR TITLE
Trade-Dangerous as a module

### LINKED ISSUE #32: would like setup.py with defined entry_points etc
I would like to have someway to do a proper install of this and if entry_points are defined one could get, for example, a trade.exe that works on windows. 
If the package were published on pypi it could even be installed by pip (yay).

I can imagine that this will be difficult without moving code into a namespace for the package.

This is a wish from my side and a question if you would like some help with it.

### PR DESCRIPTION
**Pull request by kmpm**
Changed the structure of the project to fit the recommended layout of a python project that is to be published to pypi.
This will fix #32.

__Some features/changes/pros__
- If published to pypi, installation by doing `pip3 install tradedangerous`
- Possible to use tradedangerous as a requirement in another project and just import as usual.
  Ex. `from tradedangerous import tradedb, tradenv, plugins`
- Setup.py has a configured endpoint for trade that in windows will generate a `trade.exe` in the 
  python path. Other OSes will get their native style of endpoints.
- The `data` will be recreated wherever current working directory is or the location can be controlled by
  the environment variable `TD_DATA`. (All nessecary files can be found in `tradedangerous/templates`
- Automated tests and coverage report using pytest, tox and coverage. (about 45% code coverage atm.)
- Config file for using the free travis-ci.org testing
- Started documentation using sphinx in the `docs/` folder
- Changes to .gitignore to accomodate venv, packages and similar.

__Cons__
- Nearly all files that previously were in root is now in the `tradedangerous` folder.
- Any other developer using Trade-Dangerous included in their own project will have to 
  change how they integrate it. (after first time it will be much easier by installing an updated version
  from pypi)
- The .sln and .pyproj files will need a remake to accommodate the new folder structure.

### CODE REVIEW

**Comment by kmpm** [comment]
python-symantic-release does not look to complicated to integrate, fun almost :)

**Comment by kmpm** [comment]
- `semantic-release` will only bump version on master branch
- there will be need for an initial `v0.0.1` tag on some commit
- owner of the repo will need to create an account on pypi and configure travis as described in the
  documentation of python-sematic-release. 

project is not configured in .travis.yml yet but you should be able to play around some.

**Comment by kmpm** [comment]
It tried to publish once for each python version in test and that was no good.
Now there is a deploy stage that only run once and on master branch.

**Comment by eyeonus** [comment]
It seems I do not have push access to your repo.

I've got a couple changes to make before I merge this in.

**Comment by eyeonus** [comment]
Let me know when you've given me push access to the module-ify branch at the least, then I'll push the changes I need to make and merge it in.

**Comment by kmpm** [comment]
You should have push access now

**Pull request closed without merging**
