### PR TITLE
Adding some colorization for readability, defaulting to off

### PR DESCRIPTION
**Pull request by skorn**
This adds colorized output to trade run results. By default no change (always backward compatible), but can be enabled with --colorize/-c option.
I added definitions for many colors that aren't actually used, mostly in case colors want to change or to colorize other parts of the output.

### CODE REVIEW

**Comment by eyeonus** [comment]
I'd like to see an example of the output, and that mess of if statements should be folded up into a dict, but  I see no reason not to include this.

Have you checked that it works, both in the GUI as well as in console?

**Comment by eyeonus** [comment]
https://www.codementor.io/kishanmehta/how-to-handle-switch-case-in-python-pj7q08bjj

**Comment by skorn** [comment]
Acknowledging comments, updated PR incoming.

**Comment by eyeonus** [comment]
Getting ready for work, so I don't have time to look at it right now.

I'll check it out after.

In the meantime, if you could post a screenshot of the output, that'd be appreciated.

**Comment by skorn** [comment]
Screen Shot 2019-08-30 at 11 41 06 AM

Working on GUI (doesn't work for me from v10.5.5 tag though either)

**Comment by skorn** [comment]
Ok I got "run" to work in the GUI (it was stripping arguments from required so "--credits 5000" became "5000", made it so it doesn't strip if it starts with "--" so positional ones still are stripped properly).

As for colorize in GUI, that doesn't seem to support color this way as it is a terminal thing. However it doesn't offer the option either so should not be any negative user impact.

**Comment by eyeonus** [comment]
I'm going to need you to give me access to your fork so I can fix this PR.

**Comment by skorn** [comment]
Sorry, I thought I had master that I forked from. 
When I ran it without --ly-per I got an error saying it was required, that's the only reason I bumped it up there.

**Comment by eyeonus** [comment]
You did, but your repo is **your** repo, so no one else has edit access unless you say they do.

--ly-per is required when using the --hops argument, not by the command itself.

**Comment by skorn** [comment]
Thanks for fixing it up. In truth I’ve only done one python project in recent memory so this was fun.

**Comment by eyeonus** [comment]
No worries. Most of it had to do with how the original author wrote the program more than anything python specific. Actually, the only pythony thing was turning the mass of ifs into a dict.

**Pull request merged**
