### PR TITLE
Update tradecalc.py

### PR DESCRIPTION
**Pull request by aadler**
Convert penalty to multiplier from decrement to prevent issues with multiple hops or very large penalties. See https://bitbucket.org/bgol/tradedangerous/issues/14/pruning-provides-better-results-frozen and https://bitbucket.org/bgol/tradedangerous/issues/15/scoring-seems-off.

### CODE REVIEW

**Comment by aadler** [comment]
Please hold off for now. See [the discussion](https://forums.frontier.co.uk/showthread.php/34986-TradeDangerous-power-user-trade-optimizer?p=6792891&viewfull=1#post6792891) on the Frontier forums in which there may be unintended consequences.

**Comment by eyeonus** [comment]
Your documentation is incorrect. The proposed change does /not/ produce a score boost between 0 and 1. Everything gets penalized.

**Comment by aadler** [comment]
Hi, @eyeonus. I'm not sure how. The key section is:
```
 if penalty < 0.01: # [aadler] Rare to be so close and prevents ZeroDiv
                        multiplier = 100.0
                    elif penalty < 1:
                        multiplier /= penalty ** (max(min(1 - lsPenalty, 1), 0))
                    else:
                        multiplier /= max(1, penalty * lsPenalty)

                score *= multiplier
```
multiplier starts at 1 (see line 911)

So if penalty <0.01 the multiplier reset to 100 and score = score * multiplier so that should work.

Now if penalty < 1 we are dividing a number less than one into one, which is always greater than one.
The "penalty" in this case bonus, is tempered by taking a root function, which always brings numbers between 0 and 1 closer to 1.

The standard light-second penalty is 0.006 (see line 142 in [run_cmd.py](https://github.com/eyeonus/Trade-Dangerous/blob/master/commands/run_cmd.py)).

So, with a distance in kilo-ls of 0.5, the penalty should become (0.5 ^ .994) which is 0.5020838 and the multiplier becomes 1/0.5020838 or ~1.99, which is a score bonus.

Is the code doing something else?

**Comment by eyeonus** [comment]
Ah, I see what you mean. I was looking specifically at the (math) function itself, which always produces a positive number, thus always a penalty of >0.

I wasn't even looking at the manipulations you referenced.

**Comment by aadler** [comment]
I'm very glad we're having this discussion, as it's becoming clear to me that my "small" bonus becomes much too string for distances of around 100 ls or lower. I thought I tempered that with the root application, but not enough. I am going to close this PR and do more research into making it more normal, yet still prevent the craziness that many long hops can bring in the current version. Thank you!

**Comment by eyeonus** [comment]
So, I'm looking at this, trying to see what the heck, and I finally decided I'm just going to graph this stuff, because what really matters is the end result- what the value of 'multiplier' is.
So, I've graphed the original code multiplier result at ls_penalties 100, 75, 50, 25, 0.5
https://goo.gl/eM8Y2U

And I've done the same for yours.
https://goo.gl/nRB6jr

In both graphs, red = 100%, green = 0.5%.

While it is fairly obvious looking at these graphs that the current method gives the best score to stations closest to .5Kls, and closer ones get less bonus, the score is always going down from there, so the farther away the station, the lower the score.

In the case of your code, though. Ick. The multiplier is all over the place.

I was thinking replacing the "(( x ^ 2 ) - x ) / 3" with "(( x ^ 3 ) / 16) - 0.0625", making no other changes, does the trick. That'll give a bonus to everything <1Kls, with closer getting more, while still sticking pretty close to the original curve.

:)

**Pull request closed without merging**
