### PR TITLE
Fix CI and semantic-release

### PR DESCRIPTION
**Pull request by kmpm**
This will... 
- test python 3.7
- bump versions
- publish to pypi.

__Requires__
- GH_TOKENS,  PYPI_USERNAME, PYPI_PASSWORD to be set in Travis
- A previous version tag set in git with the format `v1.2.3`. The __v__ is important.
  The `version.py` file now points to 9.5.5 so make sure there is a `v9.5.5` tag on
  a suitable commit.

This is tested as far as I can get without publishing to the 'live' pypi server. I did a scripted-not-using-sematic-release-upload-to-pypi to test.pypi.org and then removed the project.

You should be the owner of the project on pypi so I let you do the first publish. If you want to do it manually...
```
python3 setup.py sdist bdist_wheel
twine upload -u <username> -p <password> dist/*
```
If you wan't to you could add me as a maintainer on the project in pypi after first publish.

### CODE REVIEW

**Comment by eyeonus** [comment]
I sent you a collaborator invite. You can push directly to master. You don't need to PR.

**Comment by eyeonus** [comment]
Everything that needs to be set up by me is set up.

Travis is failing to build.
```
$ semantic-release publish
Current version: 9.5.5
Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list ...v9.5.5 --
  stderr: 'fatal: bad revision '...v9.5.5'
'
The command "semantic-release publish" exited with 1.
```

**Comment by kmpm** [comment]
semantic-release tries to update v9.5.5 to v9.5.5.... 

- Did you add the tag before or after push. 
  If after then travis might have checked out the code before the tag existed? 
- If it was tagged after then what happens if you do a rebuild on the full last build in travis. 
  (should be a button on the top somewhere)

**Comment by eyeonus** [comment]
Before. The tag was added automatically when the branch was merged in.

**Comment by eyeonus** [comment]
https://github.com/relekang/python-semantic-release/issues/111

**Comment by eyeonus** [comment]
https://travis-ci.org/eyeonus/Trade-Dangerous/jobs/490760986

**Pull request closed without merging**
